version: '3'

services:

  app:
    build: ./formation_data_of_clients
    container_name: app_formation_data_of_clients
    extra_hosts:
      - "prod.offenbach-debussy.ru prod:194.67.92.2"
    command:
      - python3
      - banks.py
    restart: unless-stopped

    ports:
      - 5553
      - 25
      - 80
      - 8080

    environment:
      ENGINE: postgresql+psycopg2://postgres:Vfrcvfrc1@data_base_lids:5432/parse
      MONGO_URL: mongodb://db_mongo:27017

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    depends_on:
      - db
      - nginx
      - db_mongo

  app_resending_and_delete:
    build: ./resending_and_delete_email
    container_name: app_resending_and_delete
    command:
      - python3
      - resending_and_delete.py
    restart: unless-stopped

    ports:
      - 5556
      - 25

    environment:
      MONGO_URL: mongodb://db_mongo:27017
    depends_on:
      - db
      - nginx
      - db_mongo
      - app

  app_parse_base:
    build: ./parse_base
    container_name: app_parse_base
    command:
      - python3
      - base_parse_async.py
    restart: unless-stopped

    ports:
      - 5557

    environment:
      ENGINE: postgresql+psycopg2://postgres:Vfrcvfrc1@data_base_lids:5432/parse

    volumes:
        - ./db_postgresql:/var/lib/postgresql/data/pgdata
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: data_base_lids
    restart: unless-stopped

    volumes:
      - ./db_postgresql:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: Vfrcvfrc1
      POSTGRES_USER: postgres
      POSTGRES_DB: parse
      PGDATA: /var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "5555:5555"
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=5555

  db_mongo:
    image: mongo:latest
    container_name: db_mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    depends_on:
      - db
    volumes:
      - ./db_mongo:/data/db
#      - "/etc/localtime:/etc/localtime:ro"
#      - "/etc/timezone:/etc/timezone:ro"

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf.d
    depends_on:
      - pgadmin

volumes:
       db_postgresql:
       db_mongo:
